import { getPosts } from '@/services/PostService';
import { getTags } from '@/services/TagService';
import { ReturnPromiseType } from '@/types';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

interface IProps {
  tags: ReturnPromiseType<typeof getTags>;
  posts: ReturnPromiseType<typeof getPosts>;
}

const Home: NextPage<IProps> = ({ tags, posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello world!
      {tags?.tags?.data?.map((tag) => (
        <li key={tag.attributes.key}>{tag.attributes.label}</li>
      ))}
      {posts?.data?.map((post) => (
        <a href={`/posts/${post.attributes.uid}`} key={post?.attributes?.uid}>
          {post?.attributes?.title}
        </a>
      ))}
      <div>total of {tags.tags.meta.pagination.total} tags</div>
    </div>
  );
};

export const getStaticProps: GetStaticProps<IProps> = async (context) => {
  const tags = await getTags();
  const posts = await getPosts({ keyword: '' });
  return { props: { tags, posts } };
};

export default Home;
