export const NEXT_PUBLIC_ALGOLIA_APP_ID =
  process.env.NEXT_PUBLIC_ALGOLIA_APP_ID ?? '';
export const NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY =
  process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY ?? '';
export const ALGOLIA_SEARCH_ADMIN_KEY =
  process.env.ALGOLIA_SEARCH_ADMIN_KEY ?? '';
