name: "algolia indexing"
on:
  push:
    branches:
      - main
    paths:
      - "app-portfolio-2023/src/content/**"
  workflow_dispatch:

jobs:
  ts-node-indexing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      # https://github.com/pnpm/action-setup
      # pnpm cache setup
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      # --- end of pnpm cache setup
      - run: pnpm install
      - name: create env file
        working-directory: ./app-portfolio-2023
        run: |
          touch .env
          echo ALGOLIA_SEARCH_ADMIN_KEY=${{ secrets.ALGOLIA_SEARCH_ADMIN_KEY }} >> .env
          echo NEXT_PUBLIC_ALGOLIA_APP_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }} >> .env 
          echo NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }} >> .env
      - name: "@sungryeol/lib build"
        run: pnpm run build
        working-directory: ./lib
      - run: pnpm run search-index
        working-directory: ./app-portfolio-2023
