name: "algolia indexing"
on:
  push:
    branches:
      - main
    paths:
      - "/app-portfolio-2022/content/**"
  workflow_dispatch:

jobs:
  ts-node-indexing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - name: create env file
        working-directory: ./app-portfolio-2022
        run: |
          touch .env
          echo ALGOLIA_SEARCH_ADMIN_KEY=${{ secrets.ALGOLIA_SEARCH_ADMIN_KEY }} >> .env
          echo NEXT_PUBLIC_ALGOLIA_APP_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }} >> .env 
          echo NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }} >> .env
          echo NEXT_PUBLIC_TINA_CLIENT_ID=${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }} >> .env
          echo TINA_TOKEN=${{ secrets.TINA_TOKEN }} >> .env
      - name: "@sungryeol/lib build"
        run: pnpm run build
        working-directory: ./lib
      - name: "@sungryeol/app-portfolio-2022 build for tinaCMS generated type files"
        run: pnpm run build
        working-directory: ./app-portfolio-2022
      - run: pnpm run search-index
        working-directory: ./app-portfolio-2022
